[package]
name = "polycubes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.12", features = ["derive"] }
itertools = "0.11.0"
ndarray = "0.15.6"
rand = "0.8.5"
time-humanize = "0.1.3"
